matrix:
  include:
    - language: csharp
      mono: none
      sudo: required
      dist: xenial
      addons:
        sonarcloud:
          organization: "pmozola-github"
      dotnet: 2.2
      install:
      - dotnet tool install --global dotnet-sonarscanner
      - dotnet restore src/API
      before_script:
      - export PATH="$PATH:$HOME/.dotnet/tools"
      script:
      - cd src/API
      - dotnet sonarscanner begin /k:"FifaLeague" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="$SONAR_TOKEN" || true
      - dotnet build
      - dotnet sonarscanner end || true