matrix:
  include:
    - language: csharp
      mono: none
      sudo: required
      os: windows
      addons:
        sonarcloud:
          organization: "pmozola-github"
      dotnet: 2.2
      script:
      - build.cmd