matrix:
  include:
    - language: csharp
      mono: none
      sudo: required
      dist: xenial
      install: true
      addons:
        sonarcloud:
          organization: "pmozola-github"
          token:
            secure: "$SONAR_TOKEN"
      dotnet: 2.2
      before_script:
      - chmod a+x ./build.sh
      script:
      - ./build.sh
      - sonar-scanner