matrix:
  include:
    - language: csharp
      mono: none
      sudo: required
      os: windows
      script:
<<<<<<< HEAD
      - powershell build.ps1
=======
      - SonarScanner begin /k:"pmozola_FifaLeague" /d:sonar.organization="pmozola-github" /d:sonar.language="cs" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="9f60fa7128dc42b1d1c750143dbc19f030de056e"
      - ./build.sh
      - SonarScannere end /d:sonar.login="9f60fa7128dc42b1d1c750143dbc19f030de056e"
>>>>>>> parent of 2ad3e50... Update .travis.yml
