matrix:
  include:
    - language: csharp
      mono: none
      sudo: required
      dist: xenial
      install: 
        - dotnet tool install --global dotnet-sonarscanner
      addons:
        sonarcloud:
          organization: "pmozola-github"
      dotnet: 2.2
      before_script:
      - chmod a+x ./build.sh
      - export PATH="$PATH:/home/travis/.dotnet/tools"
      script:
      - cd src/API
      - dotnet restore
      - dotnet sonarscanner begin /k:"FifaLeague" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="$SONAR_TOKEN"
      - dotnet build
      - dotnet sonarscanner end